version: '3.8'

services:
  postgresdb:
    image: postgres
    container_name: ecommerce-nahuel417-postgresdb
    env_file: ./.env.development
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: ecommerce-nahuel417-app
    depends_on:
      - postgresdb
    env_file: ./.env.development
    ports:
      - '3000:3000'

volumes:
  postgres_data:
